### ISSUE TITLE
Current install returns a 404 error when trying to download the pcoip-client from Teradici

### ISSUE THREAD

**Issue by jamesrustad** [ppira/pcoip-client#12]
Current installation returns an error:

```
$ makepkg -si
==> Making package: pcoip-client 22.01.0-2 (Sun 19 Jun 2022 08:20:41 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading pcoip-client_22.01.0-20.04_amd64.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   324    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://dl.teradici.com/DeAdBCiUYInHcSTy/pcoip-client/deb/ubuntu/pool/focal/main/p/pc/pcoip-client_22.01.0-20.04/pcoip-client_22.01.0-20.04_amd64.deb
    Aborting...
```

I tried grabbing an older binary from https://downloads.teradici.com/ubuntu/pool/non-free/p/pcoip-client/ but couldnt get the makepkg script to run correctly.

This was not the case up to about 3 weeks ago when I sucessfully installed this on another machine. Going back to that machine today to try and remake the package returns the same error.

**Comment by ppira** [comment]
Their binary package probably went missing. It works for me after updating to 22.04.0. "git pull" and try again.

**Comment by jamesrustad** [comment]
Confirmed working now. Thanks for the quick fix!
