### ISSUE TITLE
Missing libsvtav1enc.so

### ISSUE THREAD

**Issue by Groogy** [ppira/pcoip-client#13]
Hi again!

Seems to have been an update and something is missing. Can't launch the client as it gives me an error for a missing library.
```
pcoip-client: error while loading shared libraries: libSvtAv1Enc.so.0: cannot open shared object file: No such file or directory
```

I do have the package `svt-av1` installed. (Version 1.1.0-1, might be that it wants 0.x)

**Comment by ppira** [comment]
Try updating to pcoip-client 22.04. It is linked to libSvtAv1Enc.so.1. Works for me.

**Comment by Groogy** [comment]
I am running with 22.04. It is still trying to use libsvtav1enc.so.0 for me. Tried to remove and clean it out again but still getting same behavior. Ran `ldd` on it and it does give me `libSvtAv1Enc.so.0 => not found`. Feels weird since from what I understand you just take the debian package and unpack it right?

Is there anything I can do to get you some more info?

**Comment by ppira** [comment]
Double-check the version of pcoip-client.

strings /usr/bin/pcoip-client|grep 22.04

**Comment by Groogy** [comment]
So `pacman -Q --info pcoip-client | grep Version` gave me `Version         : 22.04.0-1`
But ran also strings like you suggested and that gave me:
```
22.04.0
22.04.0_@ece359c199
2022-04-12T15:38:31Z
22.04.0.ece359c199
```

**Comment by ppira** [comment]
Thats odd. Are you sure you are running /usr/bin/pcoip-client? Try running it in a terminal with:

`/usr/bin/pcoip-client`

**Comment by Groogy** [comment]
Yepp seems like it, I can't find any other pcoip-client in the system either.

**Comment by ppira** [comment]
I'm out of ideas. This is merely a repackage of Teradici's debian package.
`ldd` on my system:
```
ldd /usr/bin/pcoip-client|grep libSvt
	libSvtAv1Enc.so.1 => /usr/lib/libSvtAv1Enc.so.1 (0x00007f69f23de000)
```

**Comment by Groogy** [comment]
I'll try fiddling about manually a bit and see if I can get it to work.
