### ISSUE TITLE
add dependences

### ISSUE THREAD

**Issue by walmins** [ppira/pcoip-client#19]
Hello,
thank you for the project :+1: 
Can you please add to README then it's mandatory to install some dependency for Arch Linux:

- patchelf
- qt5-networkauth
- qt5-quickcontrols
- qt5-webengine
- glfw
- openssl-1.0

Thanks

**Comment by ppira** [comment]
Why? All dependencies are listed in PKGBUILD.
"makepkg -s" will install them and build the package.
