### ISSUE TITLE
Errors running pcoip-client

### ISSUE THREAD

**Issue by deadmeu** [ppira/pcoip-client#2]
After successfully building and installing the package, trying to run pcoip-client throws the following errors:

`pcoip-client: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory`
Resolution: **Fixed by installing `glfw`**

`pcoip-client: error while loading shared libraries: libboost_regex.so.1.65.1: cannot open shared object file: No such file or directory`
I have `boost-libs` 1.69 installed, but the error persists.

Any ideas?

**Comment by ppira** [comment]
Thanks for testing, glfw-x11 dependency was missing and libbost-regex-1.65 is now integrated in the build process. "git pull" and try again

**Comment by deadmeu** [comment]
makepkg is now failing to build:
```
bsdtar: could not chdir to 'libboost-regex'

==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by ppira** [comment]
Forgot to create a directory, please try again. I'm on mobile so I have no ability to test anything myself.

**Comment by deadmeu** [comment]
@ppira No worries - thanks for taking the time to fix these errors. Being able to run this client on Arch would be amazing for me. :smile: 



> Forgot to create a directory, please try again. I'm on mobile so I have no ability to test anything myself.

`makepkg` is building just fine now, but running `pcoip-client` is now throwing:
`pcoip-client: error while loading shared libraries: libicui18n.so.63: cannot open shared object file: No such file or directory`

**Comment by ppira** [comment]
You need "icu63" from AUR. Dependencies updated.

**Comment by ppira** [comment]
Works for me now.

**Comment by deadmeu** [comment]
Works for me as well, thanks @ppira!
