### ISSUE TITLE
URGENT!!! The pcoip client deb package no longer exists to be downloaded

### ISSUE THREAD

**Issue by cogsfx** [ppira/pcoip-client#22]
Hi 

I reinstalled my arch linux as I had to do an upgrade and wanted to start clean and as I tried to install pcoip-client I got the following error upon running makepkg -si

==> ERROR: Failure while downloading https://dl.teradici.com/DeAdBCiUYInHcSTy/pcoip-client/deb/ubuntu/pool/focal/main/p/pc/pcoip-client_23.01.1-20.04/pcoip-client_23.01.1-20.04_amd64.deb
Aborting...

This happened 5 minutes ago

**Comment by b0ssi** [comment]
It looks like the current client's download is here: https://docs.teradici.com/find/product/hp-anyware/2024.03/software-client-for-linux.

**Comment by cogsfx** [comment]
I agree, but getting that to work in arch with my knowledge and experience is almost impossible. I tried a few times and got stuck when it was asking for libprotobuf.so.23  even though I had it installed.

**Comment by ppira** [comment]
Try now.

**Comment by b0ssi** [comment]
FYI, installs and starts up `pcoip-client 23.01.1-2` for me, no further testing done, thank you.

**Comment by cogsfx** [comment]
Just tried now and it works! Awesome! Thanks!!
