### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by AWhetter** [ppira/pcoip-client#5]
The most recent version seems to be missing a couple of dependencies. Without the pcsclite package installed I get the following error:

```
pcoip-client: error while loading shared libraries: libpcsclite.so.1: cannot open shared object file: No such file or directory
```

Without qt5-quickcontrols installed I get

```
qrc:/qml/DomainLoginInteraction.qml:2:1: module "QtQuick.Controls" is not installed 
     import QtQuick.Controls 1.4 
     ^
```

**Comment by ppira** [comment]
Thank you for your report. Fixed in master.

**Comment by AWhetter** [comment]
Thanks for the fast fix! :heart:
