### ISSUE TITLE
Undefined symbol: libusb_open_fd

### ISSUE THREAD

**Issue by Groogy** [ppira/pcoip-client#7]
Hi! Do you know if pcoip needs a very specific version of libusb? I can launch it but when I try to connect I get this error:

```
pcoip-client: symbol lookup error: /usr/lib/x86_64-linux-gnu/pcoip-client/libpcoip_core.so: undefined symbol: libusb_open_fd
```
Tried disabling it in the config file but no dice. I am sitting on libusb `1.0.24-2`

**Comment by ppira** [comment]
Hi

Then you have done a lot more testing than me. I have no idea of why this fails. Ubuntu's libusb-1.0 version is 1.0.23-2 which should be fairly similar but they bumped the (minor) library version from 0.2.0 to 0.3.0 between 1.0.23 and 1.0.24. I'll have go at bundling the ubuntu libusb-1.0 package similarly to the way I bundle all other versioned dependencies.

**Comment by ppira** [comment]
Found it. They do bundle libusb-1.0 which I erroneously removed. Please test it again.

**Comment by Groogy** [comment]
Yepp that fixed it! Thank you!
