### ISSUE TITLE
Clipboard not sharing between local and remote machines

### ISSUE THREAD

**Issue by LyuboslavAngelov** [ppira/pcoip-client#9]
Hi, thanks so much for creating this package. I have just noticed that the clipboard doesn't seem to be sharing between the machines.
I'm using Manjaro XFCE - 5.10.93-1-MANJARO. Any ideas why this might be the case?

**Comment by ppira** [comment]
Yes, this is on purpose. I have omitted the clipboard sharing plugin.

**Comment by LyuboslavAngelov** [comment]
Ah, is there any reason why? Any plans to add it in?
